"""empty message

Revision ID: 152391165a11
Revises: 007056d3a0f1
Create Date: 2023-06-07 23:38:48.704967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152391165a11'
down_revision = '007056d3a0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('categoryid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product', 'category', ['categoryid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'categoryid')
    op.drop_table('category')
    # ### end Alembic commands ###
